name: PR Deploy
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy PR
        uses: ./.github/actions/pr-deploy
        with:
          server_host: ${{ secrets.HOST }}
          server_username: ${{ secrets.USERNAME }}
          server_password: ${{ secrets.PASSWORD }}
          server_port: ${{ secrets.PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          dir: '.'
          dockerfile: 'Dockerfile'
          exposed_port: '5000'
          compose_file: 'docker-compose.yml'
